# Generated by Django 5.1.7 on 2025-03-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('decription', models.TextField(blank=True, null=True)),
                ('app_file', models.FileField(upload_to='apps/')),
                ('version', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
