# Generated by Django 5.1.7 on 2025-03-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_apps_hub', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='App',
        ),
    ]
