# Generated by Django 5.1.7 on 2025-03-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_apps_hub', '0002_rename_video_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumnails/'),
        ),
    ]
