# Generated by Django 5.1.7 on 2025-03-25 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_apps_hub', '0003_app_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='category',
            field=models.IntegerField(choices=[(1, 'Apps'), (2, 'Games')], default=1),
        ),
    ]
